class instruction:
    def __init__(self, label, opcode, operandList):
        self.label, self.opcode, self.operandList = label, opcode, operandList

operands = {
  "NEG": 2,
  "DW": 1,
  "DD": 1,
  "DQ": 1,
  "ADD": 3,
  "SUB": 3,
  "BSR": 3,
  "BSL": 3,
  "ADC": 3,
  "SBB": 3,
  "INC": 2,
  "DEC": 2,
  "MOV": 2,
  "IMM": 2,
  "XOR": 3,
  "AND": 3,
  "OR": 3,
  "NOR": 3,
  "NAND": 3,
  "XNOR": 3,
  "NOT": 2,
  "LOD": 2,
  "STR": 2,
  "JMP": 1,
  "BRC": 1,
  "BNC": 1,
  "BRZ": 1,
  "BNZ": 1,
  "BRN": 1,
  "BRP": 1,
  "BZR": 2,
  "BZN": 2,
  "NOP": 0,
  "HLT": 0,
  "MLT": 3,
  "DIV": 3,
  "MOD": 3,
  "SQRT": 2,
  "CAL": 1,
  "RET": 0,
  "PSH": 1,
  "POP": 1,
  "BRL": 3,
  "BRG": 3,
  "BRE": 3,
  "BNE": 3,
  "IN": 2,
  "OUT": 2,
  "BOD": 2,
  "BEV": 2,
  "RSH": 2,
  "LSH": 2,
  "CMP": 2,
  "SRS": 3,
  "BSS": 3,
  "BLE": 3,
  "BGE": 3,
  "BITS": 2,
  "MINREG": 1,
  "RUN": 1,
  "MINRAM": 1,
  "IMPORT": 0,
  "NAME": 1,
  "OPS": 1,
  "REG": 1,
  "IN": 1,
  "SETE": 3,
  "SETNE": 3,
  "SETG": 3,
  "SETL": 3,
  "SETGE": 3,
  "SETLE": 3,
}
JMPnching_ops = [
  "BRP",
  "BRN",
  "BNZ",
  "BRZ",
  "BNC",
  "BRC",
  "JMP",
  "BRL",
  "BRG",
  "BRE",
  "BNE",
  "BEV",
  "BOD",
  "BGE",
  "BLE",
  "BZR",
]
headers = [
    "RUN",
    "BITS",
    "MINRAM",
    "MINREG",
    "IMPORT"
]
cmplx_subs = {
    "SRS": [],
    "BSS": [],
    "MOD": [
        instruction("", "PSH", ["<B>"]),
        instruction("", "SUB", ["<B>", "<B>", "<C>"]),
        instruction("", "BNC", ["+3"]),
        instruction("", "MOV", ["<A>", "<B>"]),
        instruction("", "JMP", ["-3"]),
        instruction("", "POP", ["<B>"]),
    ],
    "CAL": ["special"],
    "PSH": ["special"],
    "POP": ["special"],
    "MLT": ["special"],
    "DIV": [
        instruction("", "PSH", ["<B>"]),
        instruction("", "IMM", ["<A>", "0"]),
        instruction("", "SUB", ["<B>", "<B>", "<C>"]),
        instruction("", "BNC", ["+3"]),
        instruction("", "INC", ["<A>", "<A>"]),
        instruction("", "JMP", ["-3"]),
        instruction("", "POP", ["<B>"]),
    ],
    "BRL": [
        instruction("", "SUB", ["$0", "<B>", "<C>"]),
        instruction("", "BNC", ["<A>"]),
    ],
    "BRG": [
        instruction("", "SUB", ["$0", "<C>", "<B>"]),
        instruction("", "BNC", ["<A>"]),
    ],
    "BRE": [
        instruction("", "CMP", ["<B>", "<C>"]),
        instruction("", "BRZ", ["<A>"]),
    ],
    "BNE": [
        instruction("", "CMP", ["<B>", "<C>"]),
        instruction("", "BNZ", ["<A>"]),
    ],
    "BSR": [
        instruction("", "PSH", ["<C>"]),
        instruction("", "MOV", ["<A>", "<B>"]),
        instruction("", "RSH", ["<A>", "<A>"]),
        instruction("", "DEC", ["<C>", "<C>"]),
        instruction("", "BNZ", ["-2"]),
        instruction("", "POP", ["<C>"]),
    ],
    "BSR": [
        instruction("", "PSH", ["<C>"]),
        instruction("", "MOV", ["<A>", "<B>"]),
        instruction("", "RSH", ["<A>", "<A>"]),
        instruction("", "DEC", ["<C>", "<C>"]),
        instruction("", "BNZ", ["-2"]),
        instruction("", "POP", ["<C>"]),
    ],
    "CMP": [
      instruction("", "SUB", ["$0", "<A>", "<B>"])
    ],
    "ADC": [
        instruction("", "BNC", ["+3"]),
        instruction("", "ADD", ["<A>", "<B>", "<C>"]),
        instruction("", "JMP", ["+3"]),
        instruction("", "ADD", ["<A>", "<B>", "<C>"]),
        instruction("", "INC", ["<A>", "<A>"]),
    ],
    "SBB": [
        instruction("", "BNC", ["+3"]),
        instruction("", "SUB", ["<A>", "<B>", "<C>"]),
        instruction("", "JMP", ["+3"]),
        instruction("", "SUB", ["<A>", "<B>", "<C>"]),
        instruction("", "DEC", ["<A>", "<A>"]),
    ],
    "SETE": [
      instruction("", "CMP", ["<B>", "<C>"]),
      instruction("", "BNZ", ["+2"]),
      instruction("", "IMM", ["<A>", "1"]),
    ],
    "SETNE": [
      instruction("", "CMP", ["<B>", "<C>"]),
      instruction("", "BRZ", ["+2"]),
      instruction("", "IMM", ["<A>", "1"]),
    ],
    "SETG": [
      instruction("", "CMP", ["<B>", "<C>"]),
      instruction("", "BRC", ["+2"]),
      instruction("", "IMM", ["<A>", "1"]),
    ],
    "SETL": [
      instruction("", "CMP", ["<B>", "<C>"]),
      instruction("", "BNC", ["+2"]),
      instruction("", "IMM", ["<A>", "1"]),
    ],
    "SETGE": [
      instruction("", "CMP", ["<B>", "<C>"]),
      instruction("", "BRC", ["+2"]),
      instruction("", "IMM", ["<A>", "1"]),
    ],
    "SETLE": [
      instruction("", "CMP", ["<C>", "<B>"]),
      instruction("", "BRC", ["+2"]),
      instruction("", "IMM", ["<A>", "1"]),
    ],
    "BOD": [
      instruction("", "PSH", ["<B>"]),
      instruction("", "AND", ["<B>", "<B>", "1"]),
      instruction("", "BRZ", ["+3"]),
      instruction("", "POP", ["<B>"]),
      instruction("", "JMP", ["<A>"]),
      instruction("", "POP", ["<B>"]),
    ],
    "BEV": [
      instruction("", "PSH", ["<B>"]),
      instruction("", "AND", ["<B>", "<B>", "1"]),
      instruction("", "BNZ", ["+3"]),
      instruction("", "POP", ["<B>"]),
      instruction("", "JMP", ["<A>"]),
      instruction("", "POP", ["<B>"]),
    ],
    "BLE": [
      instruction("", "CMP", ["<C>","<B>"]),
      instruction("", "BNC", ["<A>"])
    ],
    "BGE": [
      instruction("", "CMP", ["<B>","<C>"]),
      instruction("", "BRC", ["<A>"])
    ],
    "BZR": [
      instruction("", "ADD", ["<B>", "<B>", "$0"]),
      instruction("", "BRZ", ["<A>"])
    ],
    "BZN": [
      instruction("", "ADD", ["<B>", "<B>", "$0"]),
      instruction("", "BNZ", ["<A>"])
    ],
    "NEG": [
      instruction("", "SUB", ["<A>", "$0", "<B>"])
    ]
}